Clean-up hardcoded vscode messages names
eclipse-cdt-cloud/vscode-trace-extension pull request #121
Opened 2023-03-31 23:16 UTC by hriday-panchasara

Fixes #68

2023-04-04 17:12 UTC, hriday-panchasara commented
> This PR doesn't build successfully for me locally (running `yarn` a few consecutive times), after rebasing it on latest master commit [b603bb0](https://github.com/eclipse-cdt-cloud/vscode-trace-extension/commit/b603bb08735a056a2d526649c227f9b0ff316e41). Can you rebase it in here too, so we may see what CI says?

Rebased on latest master and it builds for me, could you check and see if build error's still exist?

2023-04-04 18:49 UTC, marco-miller commented
> > This PR doesn't build successfully for me locally (running `yarn` a few consecutive times), after rebasing it on latest master commit [b603bb0](https://github.com/eclipse-cdt-cloud/vscode-trace-extension/commit/b603bb08735a056a2d526649c227f9b0ff316e41). Can you rebase it in here too, so we may see what CI says?
> 
> Rebased on latest master and it builds for me, could you check and see if build error's still exist?

Yes, it builds the first time locally and with CI herein. However, running `yarn` more than just once leads to these build errors below, not there with master commit b603bb0. More notes follow down below.

```
ERROR in ./src/trace-explorer/available-views/trace-explorer-available-views-webview-provider.ts 7:0-90
Module not found: Error: Can't resolve 'vscode-trace-webviews/lib/common/vscode-message-manager' in '/home/user/git/vscode-trace-extension/vscode-trace-extension/src/trace-explorer/available-views'
 @ ./src/extension.ts 5:0-135 12:35-70 13:73-117
ERROR in ./src/trace-explorer/opened-traces/trace-explorer-opened-traces-webview-provider.ts 7:0-90
Module not found: Error: Can't resolve 'vscode-trace-webviews/lib/common/vscode-message-manager' in '/home/user/git/vscode-trace-extension/vscode-trace-extension/src/trace-explorer/opened-traces'
 @ ./src/extension.ts 6:0-133 10:31-68 11:73-119
ERROR in ./src/trace-viewer-panel/trace-viewer-webview-panel.ts 5:0-90
Module not found: Error: Can't resolve 'vscode-trace-webviews/lib/common/vscode-message-manager' in '/home/user/git/vscode-trace-extension/vscode-trace-extension/src/trace-viewer-panel'
 @ ./src/trace-explorer/analysis-tree.ts 3:0-84 44:4-39
 @ ./src/extension.ts 3:0-66 21:33-49
3 errors have detailed information that is not shown.
Use 'stats.errorDetails: true' resp. '--stats-error-details' to show it.
webpack 5.76.0 compiled with 3 errors in 1943 ms
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
lerna ERR! yarn run prepare exited 1 in 'vscode-trace-extension'
```

- Above, I removed a few redundant lines and parts from the original log.
- I'm unable to rebuild even if removing all `node_modules` locally.
- Using yarn --version `1.22.19` locally; along with nvm `v16.19.1`, the previous LTS version (now 16.20).

2023-04-04 18:50 UTC, marco-miller requested changes
(Per above.) -Please let me know how running `yarn` multiple times goes for you @hriday-panchasara; thanks. If need be, we may ask another Reviewer's own local build trials to compare.

2023-04-04 23:22 UTC, hriday-panchasara commented
> (Per above.) -Please let me know how running `yarn` multiple times goes for you @hriday-panchasara; thanks. If need be, we may ask another Reviewer's own local build trials to compare.

Yup, its failing for me. Not sure why, the IDE does not throw any warnings and the package.json of `vscode-trace-extension` does list `vscode-trace-webviews` as a dependency. Its something related to the configuration in pacakge.json/tsconfig.json of one of these pacakages, but I can't wrap my head around what the exact issue is

2023-04-05 14:24 UTC, marco-miller commented
> > (Per above.) -Please let me know how running `yarn` multiple times goes for you @hriday-panchasara; thanks. If need be, we may ask another Reviewer's own local build trials to compare.
> 
> Yup, its failing for me. Not sure why, the IDE does not throw any warnings and the package.json of `vscode-trace-extension` does list `vscode-trace-webviews` as a dependency. Its something related to the configuration in pacakge.json/tsconfig.json of one of these pacakages, but I can't wrap my head around what the exact issue is

You could try starting this change all over again, only applying one single code change at a time; to confirm `yarn && yarn` each time. This might help you spot which exact diff happens to break the rebuild, thus knowing how to fix that maybe.

2023-04-25 18:03 UTC, bhufmann commented
I'm able to reproduce the issues after the 2nd build. 

Just for clarification, each webview runs an own application that is bundle using webpack. During the build the webpack output of vscode-trace-webview is stored in the vscode-trace-extension/pack directory and the vscode-trace-extension bundles it into the VsCode extension. So, the dependency in vsocde-trace-extension\package.json is not really needed. I suspect it's there to make sure that the webpack outputs are built first. To be able to re-use source code directly like the message definitions in this PR, I guess the build is not setup properly. However, I can't pin-point to what to change at the moment. We could try to re-structure the code so that share code are in a separate package, e.g. vscode-trace-common and try to hook it up. Alternatively, the vscode-trace-webviews could be moved into vscode-trace-extension directory and the build process updated accordingly. These are just suggestions and without trying it I can't say for sure if they work.

2023-04-26 19:44 UTC, hriday-panchasara commented
> I'm able to reproduce the issues after the 2nd build.
> 
> Just for clarification, each webview runs an own application that is bundle using webpack. During the build the webpack output of `vscode-trace-webview` is stored in the `vscode-trace-extension/pack` directory and the `vscode-trace-extension` bundles it into the VsCode extension. So, the dependency in `vsocde-trace-extension\package.json` is not really needed. I suspect it's there to make sure that the webpack outputs are built first.
> 
> To be able to re-use source code directly like the message definitions in this PR, I guess the dependencies are not setup properly. However, I can't pin-point to what to change to fix it at the moment. We could also try to re-structure the code so that shared code is in a separate package, e.g. `vscode-trace-common` and try to hook it up. Alternatively, the `vscode-trace-webviews` directory could be moved into `vscode-trace-extension` directory and the build process updated accordingly. These are just suggestions and without trying it I can't say for sure if they work.

Thanks for the suggestions Bernd. I have restructured the code and put the `vscode-message-manager.ts` in a separate package called `vscode-trace-common`. It builds successfully for me locally. Let me know if this is acceptable

2023-05-05 12:52 UTC, bhufmann requested changes

2023-05-05 12:52 UTC, bhufmann commented on vscode-trace-common/src/messages/vscode-message-manager.ts
> +    SAVE_AS_CVS: 'saveAsCsv',
should be SAVE_AS_CSV

2023-05-05 12:52 UTC, bhufmann commented on vscode-trace-common/src/messages/vscode-message-manager.ts
>  export class VsCodeMessageManager extends Messages.MessageManager {
the package.json is missing dependency to traceviewer-base

2023-05-05 13:52 UTC, bhufmann reviewed
LGTM. Since I changed some parts @marco-miller could you please review this one too? Thanks.

2023-05-05 13:59 UTC, bhufmann commented on vscode-trace-common/src/messages/vscode-message-manager.ts
> +<<<<<<< HEAD
my mistake

2023-05-05 16:36 UTC, hriday-panchasara commented
> LGTM. Since I changed some parts @marco-miller could you please review this one too? Thanks.

Thanks Bernd, the refactor looks good to me

2023-05-05 17:46 UTC, marco-miller approved these changes
LGTM now, thanks, I can `yarn` multiple times locally.

2023-05-05 18:33 UTC, bhufmann approved these changes
Looks good to me too. Thanks everybody involved.

2023-05-05 18:33 UTC, merged