Disposes trace panel when trace removed
eclipse-cdt-cloud/vscode-trace-extension pull request #127
Opened 2023-04-18 17:58 UTC by ngondalia

* Appropriate signal handling for removed traces
* Edited behaviour for the "X" button in the "opened traces" view

Fixes #104

Signed-off-by: Neel Gondalia ngondalia@blackberry.com

2023-04-18 20:53 UTC, bhufmann requested changes
Works well... just a small typo to fix. Thanks!

2023-04-18 20:53 UTC, bhufmann commented on vscode-trace-webviews/src/trace-explorer/opened-traces/vscode-trace-explorer-opened-traces-widget.tsx
> +      // ExperimentSelected handler is registered in the constrictor (upstream code), but it's
typo: `constrictor` -> `constructor`

2023-04-20 18:00 UTC, bhufmann requested changes
LGTM. Thanks!

2023-04-20 18:00 UTC, bhufmann approved these changes

2023-04-21 15:23 UTC, hoangphamEclipse commented
LGTM.

2023-04-21 15:34 UTC, merged