Propogate Output Data Changed Signal
eclipse-cdt-cloud/vscode-trace-extension pull request #180
Opened 2023-09-11 14:45 UTC by ngondalia

This commit handles the new Output_Data_Changed signal in the trace viewer container. This signal
notifies the appropriate outputs to refresh/re-fetch data from the server and re-render.

This is the follow up commit of https://github.com/eclipse-cdt-cloud/theia-trace-extension/pull/1006

Signed-off-by: Neel Gondalia <ngondalia@blackberry.com>

2023-09-11 20:45 UTC, hoangphamEclipse commented
Hi @ngondalia, thank you for the patch. Can you be more specific about the purpose of this patch in the commit message? How can I test this? Is this a part of a bigger change?

2023-09-11 20:46 UTC, hoangphamEclipse requested changes
Please update the commit message per my previous comment.

2023-09-11 21:16 UTC, ngondalia commented
> Please update the commit message per my previous comment.

Done. Also see https://github.com/eclipse-cdt-cloud/theia-trace-extension/pull/1006 for more context

2023-09-12 15:26 UTC, hoangphamEclipse commented
Thank you for the update @ngondalia. I went through the issue for context that your have provided. However, I don't see any calls to post this message to the web view so I cannot test it. Can you provide steps to test the code?

2023-09-12 16:55 UTC, ngondalia commented
> 
From the UI: Open an experiment and some outputs (table and timegraph)

In code: (you can hook this up to a command for testing purposes)
//Get active trace panel and experiment
const exp = TraceViewerPanel.getCurrentExperiment()
const panel = TraceViewerPanel.activePanels[exp.name]
// Get output descriptors for the experiment
 const descriptors = getTspClient().experimentOutputs(exp.UUID).getModel();

// Post the message to webview with descriptors as the payload
  panel._panel.webview.postMessage({
    command: VSCODE_MESSAGES.OUTPUT_DATA_CHANGED,
    data: JSONBig.stringify(descriptors)
  });

In the UI: the outputs should refresh (note: this only applies to table and timegraph views for now)```
```

2023-09-12 16:57 UTC, ngondalia commented
> 



> For this PR, I don't see any code that posts the `OUTPUT_DATA_CHANGED` message to the web view so I cannot test it. Can you provide steps to test the code?
```
From the UI: Open an experiment and some outputs (table and timegraph)

In code: (you can hook this up to a command for testing purposes)
//Get active trace panel and experiment
const exp = TraceViewerPanel.getCurrentExperiment()
const panel = TraceViewerPanel.activePanels[exp.name]
// Get output descriptors for the experiment
 const descriptors = getTspClient().experimentOutputs(exp.UUID).getModel();

// Post the message to webview with descriptors as the payload
  panel._panel.webview.postMessage({
    command: VSCODE_MESSAGES.OUTPUT_DATA_CHANGED,
    data: JSONBig.stringify(descriptors)
  });

In the UI: the outputs should refresh (note: this only applies to table and timegraph views for now)
```

2023-09-12 20:35 UTC, hoangphamEclipse approved these changes
LGTM. I am asking @PatrickTasse for a second review since I knows the context a bit better than me.

2023-09-13 18:42 UTC, PatrickTasse approved these changes

2023-09-14 18:22 UTC, merged