Proper Handling of the URL Configuration Change
eclipse-cdt-cloud/vscode-trace-extension pull request #204
Opened 2024-02-14 18:38 UTC by ngondalia

This commit provides proper handling of url configuration change. This fixes the issue of when the user changes the URL of the server, the user would need to reopen vscode so that all of the manangers can be initialized with the proper tspClientURL. With this commit, all tspClient dependent components are notified of a URL change.

Signed-off-by: Neel Gondalia ngondalia@blackberry.com

2024-02-15 18:00 UTC, williamsyang-work commented
Hey Neel,

I currently have a PR under review that addresses this exact problem as well.  https://github.com/eclipse-cdt-cloud/vscode-trace-extension/pull/196.

Maybe you can take a look and see if this works for you?

2024-02-26 16:14 UTC, bhufmann reviewed
I was testing this change and the URL change is propagated correctly. However, I noticed that when change the URL, the webviews don't populate and I see the error message below in the console log. In my test I changed the URL from `localhost` to `10.0.0.122`. All the updates are done but, the html of the webview is not resolve again and it has the old URL for the `connect-src`. For example, the method `resolveWebviewView()` which calls `_getHtmlForWebview` of `TraceExplorerOpenedTracesViewProvider` is only called once and hence the `connect-src` is not updated. I'm not sure how to fix that. Please note it's a general problem and not related to this change. Any ideas how to fix it?

![image](https://github.com/eclipse-cdt-cloud/vscode-trace-extension/assets/413424/72758958-643a-4ff8-a448-e53adfe6c877)

2024-02-26 17:29 UTC, ngondalia commented
> I was testing this change and the URL change is propagated correctly. However, I noticed that when change the URL, the webviews don't populate and I see the error message below in the console log. In my test I changed the URL from `localhost` to `10.0.0.122`. All the updates are done but, the html of the webview is not resolve again and it has the old URL for the `connect-src`. For example, the method `resolveWebviewView()` which calls `_getHtmlForWebview` of `TraceExplorerOpenedTracesViewProvider` is only called once and hence the `connect-src` is not updated. I'm not sure how to fix that. Please note it's a general problem and not related to this change. Any ideas how to fix it?
> 
> ![image](https://private-user-images.githubusercontent.com/413424/307864101-72758958-643a-4ff8-a448-e53adfe6c877.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDg5Njg2MTQsIm5iZiI6MTcwODk2ODMxNCwicGF0aCI6Ii80MTM0MjQvMzA3ODY0MTAxLTcyNzU4OTU4LTY0M2EtNGZmOC1hNDQ4LWU1M2FkZmU2Yzg3Ny5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwMjI2JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDIyNlQxNzI1MTRaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1jYjM1OTQxNGI5MTk4ZThiMDBhMTQxN2VmODJkZTVhZWE3ZWQyYzI1OTdkNjZlNmJjZDIyNmUxMWMzMDQ3NjJjJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.71Lbad6KMcEYSdmrbQETzQFS6YE_6bFZL7hRTJqeb5g)

I pushed a patch for it! Can you please re-test it and let me know? 

From the docs of webview.html property:
"
HTML contents of the webview.

This should be a complete, valid html document. Changing this property causes the webview to be reloaded.
"

Based on this, you can just assign the updated html content to the webview and it will get reloaded.

2024-02-26 18:11 UTC, bhufmann commented
> > I was testing this change and the URL change is propagated correctly. However, I noticed that when change the URL, the webviews don't populate and I see the error message below in the console log. In my test I changed the URL from `localhost` to `10.0.0.122`. All the updates are done but, the html of the webview is not resolve again and it has the old URL for the `connect-src`. For example, the method `resolveWebviewView()` which calls `_getHtmlForWebview` of `TraceExplorerOpenedTracesViewProvider` is only called once and hence the `connect-src` is not updated. I'm not sure how to fix that. Please note it's a general problem and not related to this change. Any ideas how to fix it?
> > ![image](https://private-user-images.githubusercontent.com/413424/307864101-72758958-643a-4ff8-a448-e53adfe6c877.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDg5Njg2MTQsIm5iZiI6MTcwODk2ODMxNCwicGF0aCI6Ii80MTM0MjQvMzA3ODY0MTAxLTcyNzU4OTU4LTY0M2EtNGZmOC1hNDQ4LWU1M2FkZmU2Yzg3Ny5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwMjI2JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDIyNlQxNzI1MTRaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1jYjM1OTQxNGI5MTk4ZThiMDBhMTQxN2VmODJkZTVhZWE3ZWQyYzI1OTdkNjZlNmJjZDIyNmUxMWMzMDQ3NjJjJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.71Lbad6KMcEYSdmrbQETzQFS6YE_6bFZL7hRTJqeb5g)
> 
> I pushed a patch for it! Can you please re-test it and let me know?
> 
> From the docs of webview.html property: " HTML contents of the webview. This should be a complete, valid html document. Changing this property causes the webview to be reloaded. "
> 
> Based on this, you can just assign the updated html content to the webview and it will get reloaded.

Yes, this did the trick. I tested it and works. Thanks.

I'm going to do a review now. Once this PR merged, @williamsyang-work will base his work on it.

2024-02-26 18:16 UTC, bhufmann requested changes

2024-02-26 18:16 UTC, bhufmann commented on vscode-trace-extension/src/trace-explorer/available-views/trace-explorer-available-views-webview-provider.ts
> +    public rerender() {
I think you can call the lines below in method `updateTraceServerUrl()`. With this you can avoid adding this public API.

2024-02-26 18:16 UTC, bhufmann commented on vscode-trace-extension/src/trace-explorer/opened-traces/trace-explorer-opened-traces-webview-provider.ts
> +    public rerender() {
I think you can call the lines below in method `updateTraceServerUrl()`. With this you can avoid adding this public API.

2024-02-26 18:16 UTC, bhufmann commented on vscode-trace-extension/src/trace-explorer/properties/trace-explorer-properties-view-webview-provider.ts
> +    public rerender() {
I think you can call the lines below in method `updateTraceServerUrl()`. With this you can avoid adding this public API.

2024-02-26 18:16 UTC, bhufmann commented on vscode-trace-extension/src/trace-explorer/time-range/trace-explorer-time-range-data-webview-provider.ts
> +    public rerender() {
I think you can call the lines below in method `updateTraceServerUrl()`. With this you can avoid adding this public API.

2024-02-26 18:16 UTC, bhufmann commented on vscode-trace-extension/src/trace-viewer-panel/trace-viewer-webview-panel.ts
> +        Object.values(TraceViewerPanel.activePanels).forEach(panel => {
I think you can call the lines below in method `updateTraceServerUrl()`. With this you can avoid adding this public API.

2024-02-26 19:58 UTC, bhufmann approved these changes
Looks good to me. Thanks a lot for this contribution.

2024-02-26 20:19 UTC, ngondalia commented
> Looks good to me. Thanks a lot for this contribution. Since you're committer, you can submit it. Please use `Rebase and Merge`.

I don't have that option. It seems like i still don't have write access.

2024-02-27 19:23 UTC, williamsyang-work commented
> > I was testing this change and the URL change is propagated correctly. However, I noticed that when change the URL, the webviews don't populate and I see the error message below in the console log. In my test I changed the URL from `localhost` to `10.0.0.122`. All the updates are done but, the html of the webview is not resolve again and it has the old URL for the `connect-src`. For example, the method `resolveWebviewView()` which calls `_getHtmlForWebview` of `TraceExplorerOpenedTracesViewProvider` is only called once and hence the `connect-src` is not updated. I'm not sure how to fix that. Please note it's a general problem and not related to this change. Any ideas how to fix it?
> > ![image](https://private-user-images.githubusercontent.com/413424/307864101-72758958-643a-4ff8-a448-e53adfe6c877.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDg5Njg2MTQsIm5iZiI6MTcwODk2ODMxNCwicGF0aCI6Ii80MTM0MjQvMzA3ODY0MTAxLTcyNzU4OTU4LTY0M2EtNGZmOC1hNDQ4LWU1M2FkZmU2Yzg3Ny5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwMjI2JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDIyNlQxNzI1MTRaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1jYjM1OTQxNGI5MTk4ZThiMDBhMTQxN2VmODJkZTVhZWE3ZWQyYzI1OTdkNjZlNmJjZDIyNmUxMWMzMDQ3NjJjJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.71Lbad6KMcEYSdmrbQETzQFS6YE_6bFZL7hRTJqeb5g)
> 
> I pushed a patch for it! Can you please re-test it and let me know?
> 
> From the docs of webview.html property: " HTML contents of the webview. This should be a complete, valid html document. Changing this property causes the webview to be reloaded. "
> 
> Based on this, you can just assign the updated html content to the webview and it will get reloaded.

Awesome find.  This bug has been on my radar for a while, I appreciate the fix!

2024-02-27 20:16 UTC, hriday-panchasara approved these changes
LGTM, thanks!

2024-02-27 20:17 UTC, merged