Provide API to attach signal listeners to signalManager
eclipse-cdt-cloud/vscode-trace-extension pull request #214
Opened 2024-03-06 21:16 UTC by ngondalia

This commit provides API to attach and remove listeners to signalManager within the extension context.

Signed-off-by: Neel Gondalia <ngondalia@blackberry.com>

2024-03-13 13:02 UTC, bhufmann commented
I'm going to review this today.

2024-03-13 15:24 UTC, bhufmann requested changes
Thanks for the contribution. I tried in a third-party extension with 2 signals ('widget activated' and 'output added'). I noticed the latter was not received. I realized that that signal was not forwarded ([see here](https://github.com/eclipse-cdt-cloud/vscode-trace-extension/blob/0a7c686c0276a9967a43d867ecc8c57989a87fed/vscode-trace-extension/src/trace-explorer/available-views/trace-explorer-available-views-webview-provider.ts#L82)) and hence cannot be called. I guess we need to add relevant signals in future pull request to be more complete. This won't prevent this PR to be merge. I would like to ask you one thing to add a brief description of the new API to the README where already other external APIs are described ([using-the-external-api](https://github.com/eclipse-cdt-cloud/vscode-trace-extension/blob/master/README.md#using-the-external-api)).

2024-03-13 16:02 UTC, ngondalia commented
> Thanks for the contribution. I tried in a third-party extension with 2 signals ('widget activated' and 'output added'). I noticed the latter was not received. I realized that that signal was not forwarded ([see here](https://github.com/eclipse-cdt-cloud/vscode-trace-extension/blob/0a7c686c0276a9967a43d867ecc8c57989a87fed/vscode-trace-extension/src/trace-explorer/available-views/trace-explorer-available-views-webview-provider.ts#L82)) and hence cannot be called. I guess we need to add relevant signals in future pull request to be more complete. This won't prevent this PR to be merge. I would like to ask you one thing to add a brief description of the new API to the README where already other external APIs are described ([using-the-external-api](https://github.com/eclipse-cdt-cloud/vscode-trace-extension/blob/master/README.md#using-the-external-api)).

Yeah - that would be nice.  Oops - i forgot to update it. I noticed that its missing the description for "addTraceServerContributor" as well - I will add that also. Thanks for reviewing!

2024-03-14 21:01 UTC, hriday-panchasara approved these changes
LGTM, thanks!

2024-03-14 21:02 UTC, merged