Implemented Item Properties View
eclipse-cdt-cloud/vscode-trace-extension pull request #86
Opened 2023-02-08 16:23 UTC by ngondalia

Changes made:

- Uses an theia independent react widget for Properties view from traceviewer-react-components
- Proper signal handling between item properties webview and extension

This will add the Item Properties View to the Trace Viewer.

Fixes #62

Signed-off-by: Neel Gondalia ngondalia@blackberry.com

2023-02-08 16:25 UTC, ngondalia commented
@bhufmann Please review

2023-02-10 14:40 UTC, bhufmann requested changes
Thanks for the contribution. It works with events table and time graph views (tested with Trace Compass trace server).

2023-02-10 14:40 UTC, bhufmann commented on vscode-trace-webviews/src/trace-explorer/views/properties/vscode-trace-explorer-tooltip-widget.tsx
> +                console.log(data);
Remove console.log

2023-02-10 14:40 UTC, bhufmann commented on vscode-trace-extension/src/trace-explorer/views/trace-explorer-properties-view-webview-provider.ts
> +/***************************************************************************************
This comment is for the `properties` directory. This directory should be under `trace-explorer` directly. The subdirectory `views` is the directory for the `available views` webview. I should have named it differently, maybe `available-views` to be clearer. Sorry, for the confusion. 

Please move `properties` and content to one level up under `trace-explorer` directory.

2023-02-10 14:40 UTC, bhufmann commented on vscode-trace-extension/src/trace-viewer-panel/trace-viewer-webview-panel.ts
> +	        case 'updateTooltip':
update to `updateProperties`

2023-02-10 14:40 UTC, bhufmann commented on vscode-trace-extension/src/trace-viewer-panel/trace-viewer-webview-panel.ts
> +	            vscode.commands.executeCommand('messages.post.propertiespanel', 'receivedTooltip', message.data);
update to `receivedProperties`

2023-02-10 14:40 UTC, bhufmann commented on vscode-trace-webviews/src/common/vscode-message-manager.ts
> +    tooltipUpdated(tooltip: { [key: string]: string }): void {
Rename tooltip to properties

2023-02-10 14:40 UTC, bhufmann commented on vscode-trace-webviews/src/common/vscode-message-manager.ts
> +        vscode.postMessage({command: 'updateTooltip', data: {tooltip}});
update tooltip to properties

2023-02-10 14:40 UTC, bhufmann commented on vscode-trace-webviews/src/trace-explorer/views/properties/index.tsx
> +import TraceExplorerProperties from './vscode-trace-explorer-tooltip-widget';
update tooltip to properties

2023-02-10 14:40 UTC, bhufmann commented on vscode-trace-webviews/src/trace-explorer/views/properties/vscode-trace-explorer-tooltip-widget.tsx
> +    tooltip: { [key: string]: string };
properties

2023-02-10 14:40 UTC, bhufmann commented on vscode-trace-webviews/src/trace-explorer/views/properties/vscode-trace-explorer-tooltip-widget.tsx
> +    static ID = 'trace-explorer-tooltip-widget';
properties

2023-02-10 14:40 UTC, bhufmann commented on vscode-trace-webviews/src/trace-explorer/views/properties/vscode-trace-explorer-tooltip-widget.tsx
> +            tooltip: {}
properties

2023-02-10 14:40 UTC, bhufmann commented on vscode-trace-webviews/src/trace-explorer/views/properties/vscode-trace-explorer-tooltip-widget.tsx
> +            case 'receivedTooltip':
Properties

2023-02-10 14:40 UTC, bhufmann commented on vscode-trace-webviews/src/trace-explorer/views/properties/vscode-trace-explorer-tooltip-widget.tsx
> +                console.log('got message');
remove console.log

2023-02-10 14:40 UTC, bhufmann commented on vscode-trace-webviews/src/trace-explorer/views/properties/vscode-trace-explorer-tooltip-widget.tsx
> +                signalManager().fireItemPropertiesSignalUpdated(message.data.tooltip);
properties

2023-02-10 14:40 UTC, bhufmann commented on vscode-trace-webviews/src/trace-viewer/vscode-trace-viewer-container.tsx
> +  private _onTooltip = (tooltip: { [key: string]: string }): void => this.doHandleTooltipSignal(tooltip);
rename to use properties in the names

2023-02-10 14:40 UTC, bhufmann commented on vscode-trace-webviews/src/trace-viewer/vscode-trace-viewer-container.tsx
> +      this._signalHandler.tooltipUpdated(tooltip);
properties

2023-02-10 14:40 UTC, bhufmann commented on vscode-trace-webviews/src/trace-viewer/vscode-trace-viewer-container.tsx
> +  private doHandleTooltipSignal(tooltip: { [key: string]: string }) {
properties

2023-02-10 14:40 UTC, bhufmann commented on vscode-trace-webviews/src/trace-viewer/vscode-trace-viewer-container.tsx
> +      signalManager().on(Signals.ITEM_PROPERTIES_UPDATED, this._onTooltip);
properties

2023-02-10 14:40 UTC, bhufmann commented on vscode-trace-webviews/src/trace-viewer/vscode-trace-viewer-container.tsx
> +      signalManager().off(Signals.ITEM_PROPERTIES_UPDATED, this._onTooltip);
same here

2023-02-10 14:40 UTC, bhufmann commented on vscode-trace-webviews/src/trace-explorer/views/properties/vscode-trace-explorer-tooltip-widget.tsx
> +        console.log('Source lookup method not implemented');
Ok we can keep that warning. Source code lookup feature needs to be improved and handled in the whole application (consistently) anyways.

2023-02-16 14:23 UTC, bhufmann requested changes
Small update to the license headers requested.

2023-02-16 14:23 UTC, bhufmann commented on vscode-trace-webviews/src/trace-explorer/properties/vscode-trace-explorer-properties-widget.tsx
> + * Copyright (c) 2023 BlackBerry Limited and contributors.
`and others` instead of `and contributors`

2023-02-16 15:04 UTC, bhufmann approved these changes
LGTM. Thanks a lot for the contribution.

2023-02-17 20:05 UTC, ngondalia commented
@bhufmann  Can you please merge it? I don't have write access to the repo.

2023-02-21 15:11 UTC, Rodrigoplp-work approved these changes

2023-02-21 15:18 UTC, merged