Add open button in "Open Traces" view
eclipse-cdt-cloud/vscode-trace-extension pull request #90
Opened 2023-02-22 00:30 UTC by hriday-panchasara

- Add opened traces contribution to openedTracesView 
- Show file picker dialog to select experiment
- Update opened traces and available views after opening

fixes #61

2023-02-22 13:42 UTC, bhufmann requested changes
Thanks for the contribution. I noticed that the dialog box is always in the background and not on top of vscode. I have use my OS's window manager to select the dialog box. Can it be brought to the top automatically?

2023-02-22 13:42 UTC, bhufmann commented on vscode-trace-extension/package.json
> +        "command": "openedTraces.openTraceFile",
It's actually a trace file. With the open dialog only a folder can be selected. Then open procedure scans for CTF traces recursively. So, this should be renamed. The open dialog only supports either folder selection or file selection, and not both.

The other, existing command that can be invoked from the file explorer and context-sensitive menu is a bit different. It allows also for selecting a single file trace (not CTF traces).

2023-02-22 13:42 UTC, bhufmann commented on vscode-trace-extension/src/trace-explorer/trace-tree.ts
> +            console.log('Cannot open trace: invalid uri for file', file);
may say instead `... invalid uri for trace`.

2023-02-22 13:42 UTC, bhufmann commented on vscode-trace-extension/src/trace-explorer/trace-tree.ts
> +    let fileURI = undefined;
rename fileURI since it's not a file

2023-02-22 13:42 UTC, bhufmann commented on vscode-trace-extension/src/trace-explorer/trace-tree.ts
> +    if (!file) {
rename `file`?

2023-02-27 21:38 UTC, bhufmann commented
> Thanks for the contribution. I noticed that the dialog box is always in the background and not on top of vscode. I have use my OS's window manager to select the dialog box. Can it be brought to the top automatically?

@hriday-panchasara any findings on this? Please let me know.

2023-02-27 23:34 UTC, hriday-panchasara commented
> > Thanks for the contribution. I noticed that the dialog box is always in the background and not on top of vscode. I have use my OS's window manager to select the dialog box. Can it be brought to the top automatically?
> 
> @hriday-panchasara any findings on this? Please let me know.

Open/Save file dialog's being opened in the background has been reported as a vscode issue with RHEL/EL systems: https://github.com/microsoft/vscode/issues/146422. The current workaround is to downgrade to <1.68 version for vscode. It seems that this issue does not affect Mac, as shown by the following recording:
[Screen Recording 2023-02-27 at 12.32.40 PM.webm](https://user-images.githubusercontent.com/92893187/221713381-b9f81799-939a-4065-9966-2e7ade116c3e.webm)

2023-02-28 01:33 UTC, bhufmann commented
> > > Thanks for the contribution. I noticed that the dialog box is always in the background and not on top of vscode. I have use my OS's window manager to select the dialog box. Can it be brought to the top automatically?
> > 
> > 
> > @hriday-panchasara any findings on this? Please let me know.
> 
> Open/Save file dialog's being opened in the background has been reported as a vscode issue with RHEL/EL systems: [microsoft/vscode#146422](https://github.com/microsoft/vscode/issues/146422). The current workaround is to downgrade to <1.68 version for vscode. It seems that this issue does not affect Mac, as shown by the following recording:

Thanks for the information. So, we are dependent on a fix in VsCode for that.

2023-02-28 01:34 UTC, bhufmann requested changes
It works fine. @hriday-panchasara Please rebase this PR and then I'll finalize the review.

2023-03-13 18:26 UTC, bhufmann requested changes
The feature works well in VsCode or Vscodium. However, when installing it in an Theia application it doesn't work. The button is visible but nothing happens when clicking on it. I guess is that the command-handler is not working in Theia and open the file dialog needs to be done differently. I would as a question on Theia discussions to get some support on how to invoke the directory chooser correctly so that it works in vscode and Theia when installing this vscode extension.

2023-03-15 12:57 UTC, bhufmann commented
> The feature works well in VsCode or Vscodium. However, when installing it in an Theia application it doesn't work. The button is visible but nothing happens when clicking on it. I guess is that the command-handler is not working in Theia and open the file dialog needs to be done differently. I would as a question on Theia discussions to get some support on how to invoke the directory chooser correctly so that it works in vscode and Theia when installing this vscode extension.
> 
> To reproduces do the following steps:
> 
>     * download theia blueprint: https://theia-ide.org/docs/blueprint_download#downloads
> 
>     * build the vsix file in this repo: yarn vsce:package
> 
>     * run theia blueprint
> 
>     * install extension from vsix file

@hriday-panchasara the latest Theia blueprint is based on Theia 1.35.0 version. It fails with that. However, when I use a Theia application based on 1.34.x it works (e.g. theia-trace-extension example electron app). It looks like that there was an issue introduced between these Theia versions. We should report that issue to the Theia community.,

2023-03-16 16:33 UTC, bhufmann approved these changes
@hriday-panchasara  I think we can merge it. The issues with Theia 1.35.0 will need to be addressed in Theia. It works successfully in VsCode and Theia 1.34.x.

2023-03-16 17:09 UTC, merged