Export DataTree to csv through showSaveDialog
eclipse-cdt-cloud/vscode-trace-extension pull request #99
Opened 2023-02-28 23:49 UTC by hriday-panchasara

Webviews run in isolated contexts that cannot access local resources. Because of this webviews could an issue with opening hyperlinks.
- Suggested fix is to use showSaveDialog from vscode api
- Users can choose file name/path
- Show success/error message after
- Depends on signal added in https://github.com/eclipse-cdt-cloud/theia-trace-extension/pull/938

Fixes #66

2023-03-06 19:09 UTC, marco-miller commented
@hriday-panchasara, should this PR be set to Draft for you to rework, given its failing CI build herein?

2023-03-07 18:34 UTC, hriday-panchasara commented
> @hriday-panchasara, should this PR be set to Draft for you to rework, given its failing CI build herein?

Yup, keeping it as draft until its dependency (https://github.com/eclipse-cdt-cloud/theia-trace-extension/pull/938) gets reviewed

2023-03-21 15:30 UTC, alexdoan3011 commented on vscode-trace-webviews/src/trace-viewer/vscode-trace-viewer-container.tsx
> +      signalManager().on(Signals.SAVE_DATATREE_CSV, this._onSaveDatatreeCSV);
I'm submitting my pull request that adds component-based drop down menu and export table for xy-output-component. Should I change the string of the signal from 'save datatree as csv' to 'save as csv' in my PR as well?

2023-03-22 15:43 UTC, bhufmann requested changes

2023-03-22 15:44 UTC, bhufmann commented on vscode-trace-webviews/src/trace-viewer/vscode-trace-viewer-container.tsx
> +      signalManager().on(Signals.SAVE_DATATREE_CSV, this._onSaveDatatreeCSV);
This is resolved with the latest update of the PR.

2023-03-23 16:26 UTC, bhufmann approved these changes
Looks good to me. Thanks!

2023-03-23 16:30 UTC, merged